export const ALMOXARIFADO_SUBCATEGORIES_BY_CATEGORY: Record<
  ALMOXARIFADO_CATEGORY,
  ALMOXARIFADO_SUBCATEGORY[]
> = {
  Implante: [
    "Implante Cone Morse",
    "Implante Hexágono Interno",
    "Implante Hexágono Externo",
    "Implante Cilíndrico",
    "Implante Cônico",
    "Implante Curto",
    "Implante Zigomático",
    "Implante Unitário",
    "Tapa Implante",
  ],
  "Componente Protético": [
    "Calcinável Reto",
    "Calcinável Angulado",
    "Pilar Cônico",
    "Pilar Estético",
    "Pilar UCLA",
    "Pilar Multiunit",
    "Mini Pilar",
    "Pilar Angulado 15º",
    "Pilar Angulado 17º",
    "Pilar Angulado 30º",
    "Parafuso Protético",
    "Parafuso Pilar",
    "Parafuso Cicatrizador",
    "Parafuso Multiunit",
    "Transferente Aberto",
    "Transferente Fechado",
    "Transferente Multiunit",
    "Analógico Externo",
    "Analógico Interno",
    "Analógico Cone Morse",
    "Cicatrizador Curto",
    "Cicatrizador Médio",
    "Cicatrizador Longo",
    "Cicatrizador Anatômico",
    "Base Metálica",
    "Cofragem",
  ],
  "Material Clínico": [
    "Luva Procedimento",
    "Luva Cirúrgica",
    "Gaze Estéril",
    "Gaze Não Estéril",
    "Campo Operatório",
    "Mascara Cirúrgica",
    "Touca Descartável",
    "Avental Cirúrgico",
    "Seringa Carpule",
    "Agulha Longa",
    "Agulha Curta",
    "Anestésico",
    "Cimento Cirúrgico",
    "Fita Hemostática",
    "Bisturi",
    "Lamina de Bisturi",
    "Caneta de Alta Rotação",
    "Broca",
    "Fresa",
    "Espelho Clínico",
    "Sugador",
    "Cânula",
    "Sugador Cirúrgico",
    "Porta Agulha",
    "Pinça Clinica",
    "Cureta",
    "Elevador Periostal",
  ],
  Outros: [
    "Caixa Cirúrgica",
    "Chave Torquímetro",
    "Chave Hexagonal",
    "Chave de Inserção",
    "Kit Cirúrgico",
    "Outro",
  ],
};
